### ISSUE TITLE
Unapproved Relief Manually Inserted 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#163]
Upon application of leave. An employee with no approved relief can manually insert any employee in the relief field and the system accept the relief and transaction. 

Build a rule to stop the transaction 

Exclude/Exception for the rule Sick leave Standard SL1 and Sick Leave SL2, reason as the HRBP or the supervisor can add a relief in the absence of the staff.

**Comment by kiranramnath** [comment]
@EmmanuelEdhedhe on which environment is this happening, I tried this on UBAUAT, with A00750, and could not recreate. Is this on ESS/MSS/X3

**Comment by EmmanuelEdhedhe** [comment]
Its on UBAUAT Environment both on ESS/MSS/X3

**Comment by MartinKruger** [comment]
application for leave was created on X3, an employee  was chosen  and was allowed to type in the employee ID of any employee but couldn't leave the collumn without selecting the employee ID of a valid relief out of 2 options. (NGA DEV)  
in ESS , an  application for leave was created, but when selecting an option for relief there were more than just 2 options. (NGA DEV)
in X3  for creating a leave request, all employees were shown rather than just 2 approved options for relief. ( UBAUAT )
could not test MSS, will test at a later stage. (NGA DEV)
lindalee

**Comment by EmmanuelEdhedhe** [comment]
Completed.
