### ISSUE TITLE
Wrong recipient for Redeployment WF Notification 

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#359]
Redeployment notification is being sent to employee A22454, who should not be gettng these notifications. This issue started today 12 March 2018 and samples of redeployment staff movements that have been sent to her are - A17587, A17092, A1758

**Comment by roberteta** [comment]
In addition, employee A22454, is being sent notifications on Sanctions approval and issued sanctions as though she is the HRBP linked with the Staff.

Please look into this as the GMD was copied in the Final warning letter issued to employee A09177 for which A22454 was wrongly copied.

**Comment by roberteta** [comment]
See sample sanction notification sent out with employee A22454 (Okafor, Ugochi) wrongly copied


From: PeopleConnect@ubagroup.com [mailto:PeopleConnect@ubagroup.com] 
Sent: Tuesday, March 13, 2018 11:56 AM
To: Ogunbona, Rotimi <rotimi.ogunbona@ubagroup.com>
Cc: Iweriebor, Emeke <emeke.iweriebor@ubagroup.com>; Ogunleye, Gbenga <Gbenga.Ogunleye@ubagroup.com>; Uzoka, Kennedy <kennedy.uzoka@ubagroup.com>; Okafor, Ugochi <Ugochi.Okafor@ubagroup.com>; WorkEthicsTeam <WorkEthicsTeam@ubagroup.com>
Subject: FINAL WARNING LETTER - Rotimi Ogunbona A09177

**Comment by janwvjaarsveld** [comment]
A blank contract was loaded on the system by OYOWO on 06/03/2018. The way that the second level supervisor is derived, this blank contract, with J0176099900002 as the position is causing problems. A22454 is the reporting to for this position.

**Comment by roberteta** [comment]
@ JW,
Thanks for the investigation and determining the root cause.  I will follow up with Bola, regarding this blank contract. I do know however that anew hire A24773 was onboarded into Bola's position J0176099900001 and to correct this anomaly, he created a new position J0176099900002 for this employee. Not sure how he managed the movement of this employee from J0176099900001 to J0176099900002.

What is the way forward to address this issue of wrong recipient for redeployment, and sanction WF notification?

**Comment by MartinKruger** [comment]
We believe the blank contact was created because the values used with the import template included values that were not complete or correct.

The employee and contract import template should actually only be used for large volume of imports and MUST be followed by the Contract Validation process. This process checks and validates the imported values. I think, in these instances, the Contract Validation was not run.

I.e. the import import directly into the tables and the validation finalise the process by applying all the business rules.

When a smaller number of employees are to be created, please follow the normal Arrival -> Employee -> Contract process to avoid similar situations going forward.

To correct the current situation, we wen through the following steps:

1. We changed the key of the blank employee record to a temp key 'SAGE_TEST'.
2. Tracked every field in every table where the temp employee was found (after key change).
3. Reset the key to blank
4. Deleted the "blank" contract.
5. Deleted the "blank" employee.
